---
- name : Install Epel-repo
  yum:
    name : epel-release
    state : present
  when : ansible_os_family == "RedHat"
  tags : install_epel

- name : Install nginx on CentOS from epel
  yum:
    name : nginx
    state : latest
  when : ansible_os_family == "RedHat"
  notify: 
    - restart_nginx
  tags : install_nginx_centos

- name : Install nginx on Ubuntu
  apt:
    name : nginx
    state : latest
  when : ansible_os_family == "Debian"
  notify:
    - restart_nginx
  tags : install_nginx_ubuntu

- name : config nginx CentOS
  template:
    src: cntnginx.conf.j2
    dest: /etc/nginx/nginx.conf
  when : ansible_os_family == "RedHat"
  notify:
    - reload_nginx
  tags : config_nginx

- name : config nginx Ubuntu
  template:
    src: ubn-nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  when : ansible_os_family == "Debian"
  notify:
    - reload_nginx
  tags : config_nginx

- name : create direcrory for content
  file:
    path: '{{ nginx_content }}'
    state: directory
    owner: root
    group: root
    mode : '0755'

- name : config custom index file
  template:
    src: index.html.j2
    dest: /var/www/content/index.html
  notify:
    - reload_nginx
  tags : create_content
  


