---
- name: Information of system
  shell: "uname -a"
  tags: uname

- name: install utilities in debian/ubuntu
  apt: name="{{ item }}" state=present update_cache=yes cache_valid_time=3600
  loop:
    - tree
    - lsof
    - traceroute
    - atop
    - nmon
    - htop
  when: ansible_pkg_mgr == "apt"
  tags: apt-package

- name: install utilites in RHEL/centOS
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - tree
    - lsof
    - traceroute
    - atop
    - nmon
    - htop
  when: ansible_pkg_mgr == "yum"
  tags: yum-package
